#!/usr/bin/env bash

set -x

inflections () {
  pushd inflections-hs
  stack2nix \
    --lts-haskell ../lts-haskell \
    --all-cabal-hashes ../all-cabal-hashes
  nix-build -A inflections "$@"
  popd
}

# inflections
case $1 in
  inflections*)
    shift
    inflections "$@"
    ;;
  *)
    inflections "$@"
esac
