#!/usr/bin/env bash
#

set -e

usage () {
  cat << EOF
Usage:
  stackage2nix-test <project> [--dry-run]
Examples:
  stackage2nix-test inflectins-hs
  stackage2nix-test stack --dry-run
EOF
}

declare DIR
if [ -z "$1" ]; then
  usage
  exit 1
else
  DIR=$1
  shift
fi

nix-build-project () {
  local -a projects
  while IFS= read -d $'\0' -r file ; do
    projects+=( $(basename "$file" .cabal) )
  done < <(find "$DIR" -maxdepth 2 -not -path '*/\.*' -type f -name '*.cabal' -print0)
  ( set -x; nix-build ${projects[@]/#/ -A } $@ )
}

stackage2nix-project () {
  ( set -x;
    stackage2nix \
      --lts-haskell ./lts-haskell \
      --all-cabal-hashes ./all-cabal-hashes \
      "$DIR/"
    )
}

stackage2nix-project "$@"
nix-build-project "$@"
