#!/usr/bin/env bash

set -e

nix-build-cabal () {
  local -a projects
  local -r dir=$1
  while IFS= read -d $'\0' -r file ; do
    projects+=( $(basename "$file" .cabal) )
  done < <(find "$dir" -not -path '*/\.*' -type f -name '*.cabal' -print0)
  (set -x; nix-build ${projects[@]/#/ -A })
}

test-project () {
  local -r dir=$1
  set -x
  stack2nix \
    --lts-haskell ./lts-haskell \
    --all-cabal-hashes ./all-cabal-hashes \
    "$dir/"
  set +x
  nix-build-cabal "$dir"
}

test-project "$1"
